- hosts: localhost
  tasks:

  - name: Add kubernetes.repo
    copy:
      dest: /etc/yum.repos.d/kubernetes.repo
      content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Remove default packages
    dnf:
      name:
      - audit
      - avahi
      - abrt
      - cups
      - gnome-maps
      - gnome-photos
      - gnome-software
      - gnome-terminal
      - PackageKit
      - pcsc-lite
      - rhythmbox
      - sssd-common
      - totem
      state: absent

  - name: Install basic tools
    dnf:
      name:
      - android-tools
      - ansible
      - bat # cat(1) clone with wings
      - bats # Bash Automated Testing System
      - bcache-tools
      - btrfs-progs
      - chromium-browser-privacy
      - conda
      - curl
      - dpkg
      - enpass
      - evolution
      - evolution-etesync
      - fd-find
      - gnome-shell-extension-appindicator
      - gnome-tweaks
      - google-chrome-stable
      - grub2-efi-x64
      - grub2-tools
      - htop
      - kubectl
      - lpf-spotify-client
      - nmap
      - mdadm
      - neovim
      - openssl
      - podman
      - python3-dnf-plugin-snapper
      - ripgrep
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
      - shim-x64
      - snapper
      - strace
      - tig
      - tilix
      - wget
      - zsh
      state: latest

  - name: profile.d alias.sh
    copy:
      dest: /etc/profile.d/alias.sh
      content: |
        # /etc/profile.d/alias.sh
        alias docker='podman'
        alias dnf='sudo dnf'
        alias k='kubectl'
        alias neovim='nvim'
        alias vi='nvim'
        alias vim='nvim'

  - name: Symlink WidevineCdm to Chromium
    file:
      src: /opt/google/chrome/WidevineCdm
      dest: /usr/lib64/chromium-browser-privacy/WidevineCdm
      owner: root
      group: root
      state: link
