- hosts: localhost
  tasks:

  - name: Add kubernetes.repo
    copy:
      dest: /etc/yum.repos.d/kubernetes.repo
      content: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Remove default packages
    dnf:
      name:
      - audit
      - avahi
      - abrt
      - cups
      - gnome-maps
      - gnome-photos
      - gnome-remote-desktop
      - gnome-software
      - gnome-terminal
      - PackageKit
      - pcsc-lite
      - rhythmbox
      - sssd-common
      - totem
      state: absent

  - name: Install basic tools
    dnf:
      name:
      - android-tools
      - ansible
      - bat # cat(1) clone with wings
      - bats # Bash Automated Testing System
      - bcache-tools
      - btrfs-progs
      - chromium-browser-privacy
      - conda
      - curl
      - dpkg
      - emacs
      - enpass
      - evolution
      - evolution-etesync
      - evolution-ews
      - fd-find
      - fedora-packager
      - flameshot
      - gcc
      - gnome-shell-extension-appindicator
      - gnome-tweaks
      - golang
      - google-chrome-stable
      - grub2-efi-x64
      - grub2-tools
      - htop
      - inkscape
      - jq
      - iotop
      - kubectl
      - langpacks-de
      - lpf-spotify-client
      - nmap
      - mdadm
      - neovim
      - openssl
      - papirus-icon-theme
      - podman
      - pulseeffects
      - python3-dnf-plugin-snapper
      - python3-language-server
      - ripgrep
      - rpmdevtools
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
      - shim-x64
      - snapper
      - strace
      - tig
      - tilix
      - wget
      - zsh
      state: latest

  - name: profile.d alias.sh
    copy:
      dest: /etc/profile.d/alias.sh
      content: |
        # /etc/profile.d/alias.sh
        alias dnf='sudo dnf'
        alias k='kubectl'
        alias neovim='nvim'
        alias vi='nvim'
        alias vim='nvim'

  - name: Symlink WidevineCdm to Chromium
    file:
      src: /opt/google/chrome/WidevineCdm
      dest: /usr/lib64/chromium-browser-privacy/WidevineCdm
      owner: root
      group: root
      state: link

  - name: /etc/default/grub
    vars:
      crypt_root: /dev/root
    copy:
      dest: /etc/default/grub
      content: |
        GRUB_TIMEOUT=5
        GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
        GRUB_DEFAULT=saved
        GRUB_DISABLE_SUBMENU=true
        GRUB_TERMINAL_OUTPUT="console"
        GRUB_CMDLINE_LINUX="rd.luks.uuid=$(blkid | sed -nE 's,{{ crypt_root }}:\sUUID="([a-fA-F0-9]{8}-([a-fA-F0-9]{4}-){3}[a-fA-F0-9]{12})"\sTYPE="crypto_LUKS",\1,p') systemd.unified_cgroup_hierarchy=0 rd.auto rhgb quiet"
        GRUB_DISABLE_RECOVERY=true
        GRUB_ENABLE_BLSCFG=true
        GRUB_ENABLE_CRYPTODISK=true
        SUSE_BTRFS_SNAPSHOT_BOOTING=true
